// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDED9qv_Ysip3uPIc1WCBlbE0_AmfXJwoE',
    appId: '1:475384191403:web:51ceed2b7210b6b4b19aee',
    messagingSenderId: '475384191403',
    projectId: 'mad-practical12',
    authDomain: 'mad-practical12.firebaseapp.com',
    storageBucket: 'mad-practical12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfwxvEAQfmy87XZX3_OUUB5fY__B6HVco',
    appId: '1:475384191403:android:cdeb5b290237e8feb19aee',
    messagingSenderId: '475384191403',
    projectId: 'mad-practical12',
    storageBucket: 'mad-practical12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD98jXgX0wYpq2yPYrQ9DklRg-f2PTAEcg',
    appId: '1:475384191403:ios:0bba23860bd89e0ab19aee',
    messagingSenderId: '475384191403',
    projectId: 'mad-practical12',
    storageBucket: 'mad-practical12.firebasestorage.app',
    iosBundleId: 'com.example.practical12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD98jXgX0wYpq2yPYrQ9DklRg-f2PTAEcg',
    appId: '1:475384191403:ios:0bba23860bd89e0ab19aee',
    messagingSenderId: '475384191403',
    projectId: 'mad-practical12',
    storageBucket: 'mad-practical12.firebasestorage.app',
    iosBundleId: 'com.example.practical12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDED9qv_Ysip3uPIc1WCBlbE0_AmfXJwoE',
    appId: '1:475384191403:web:f7a748860fe89e33b19aee',
    messagingSenderId: '475384191403',
    projectId: 'mad-practical12',
    authDomain: 'mad-practical12.firebaseapp.com',
    storageBucket: 'mad-practical12.firebasestorage.app',
  );
}
